[package]
name = "terminus"
version = "0.1.0"
authors = ["shady831213 <shady831213@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dpi_memory={git = "https://github.com/shady831213/dpi_memory"}
terminus-macros={ path = "macros" }
terminus-proc-macros={ path = "proc_macros" }
