[package]
name = "terminus"
version = "0.1.0"
authors = ["shady831213 <shady831213@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminus-spaceport={git = "https://github.com/shady831213/terminus_spaceport"}
terminus-global = { path = "global" }
terminus-macros={ path = "macros" }
terminus-proc-macros={ path = "proc_macros" }
linkme = "0.1"
xmas-elf = "0.7.0"

[workspace]
members = ["global","macros","proc_macros"]

[[test]]
name = "load_elf"
path = "top_tests/load_elf.rs"

[[test]]
name = "decode"
path = "top_tests/decode.rs"

[[example]]
name = "htif_test"
path = "top_tests/htif_test.rs"